version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - ./server/src:/usr/src/app/src
      - ./usr/src/app/node_modules
    depends_on:
      - mongo
    environment:
      - mongo_url=${mongo_url}
      - port=3001
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/public:/usr/src/app/public
      - /usr/app/node_modules
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true
  mongo:
    image: mongo:latest
    hostname: mongo
    ports:
        - 27017:27017
    volumes:
        - mongodbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${db_user}
      - MONGO_INITDB_ROOT_PASSWORD=${db_password}
      - MONGO_INITDB_DATABASE=${db_name}
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: "${mongo_url}"
    depends_on:
      - mongo
volumes:
  mongodbdata:
      driver: local
